### ISSUE TITLE
Header/logo bug on the IE11

### ISSUE THREAD

**Issue by brentrobbins** [variantstudios/bjcsteel.com#39]
Client reported the the logo in the header the bottom is hidden on the bottom using IE11 on Windows 10. Please take a screenshot of before and after fixing and paste the jumpshare links/screenshots on this ticket.

**Comment by danieljauch** [comment]
Couldn't replicate, waiting for more information from client

**Comment by brentrobbins** [comment]
It's the border missing on the logo on the bottom that's being cut off. IE11 on the left: http://jmp.sh/GsCh7Gn
